comment "--" ;
comment "{-" "-}" ;

AProgram. Program ::= [Command] ;

CommandCheck. Command ::= "check" Expr ;
CommandCompute. Command ::= "compute" Expr ;
terminator Command ";" ;

token NatIdent digit+ ;
token TrueIdent {"true"} ;
token FalseIdent {"false"} ;
token VarIdent letter (letter | digit | '_' | '\'')* ;


EVar. Expr3 ::= VarIdent ;
EConstNat. Expr3 ::= NatIdent ;
EConstTrue. Expr3 ::= TrueIdent ;
EConstFalse. Expr3 ::= FalseIdent ;

EAdd. Expr2 ::= Expr2 "+" Expr2 ;
ESub. Expr2 ::= Expr2 "-" Expr2 ;
EIsZero. Expr2 ::= "iszero" "(" Expr ")" ;

ELam. Expr1 ::= "λ" Pattern "." ScopedExpr ;
EApp. Expr1 ::= Expr1 Expr ;
EIf. Exp1 ::= "if" Exp1 "then" Exp1 "else" Exp1 ;
ELet. Expr1 ::= "let" Pattern "=" Expr1 "in" ScopedExpr ;

ETyped. Expr ::= Expr1 ":" Type ;

coercions Expr 3 ;


AScopedExpr. ScopedExpr ::= Expr1 ;


PatternVar. Pattern ::= VarIdent ;

TFunc. Type ::= Type1 "->" Type ;
TNat. Type1 ::= "Nat" ;
TBool. Type1 ::= "Bool" ;

coercions Type 1 ;
