name: STLC
version: 0.2.0
github: "tjann7/free-foil"
license: BSD3
author: "Timur Suleymanov"
maintainer: "tsuleymanov32@gmail.com"
copyright: "2025-2026 Timur Suleymanov"

extra-source-files:
  - README.md
  - LICENSE
  - grammar/STLC/Syntax.cf

synopsis: λΠ-calculus implemented in a few different ways.
category: Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/tjann7/free-foil#readme>

custom-setup:
  dependencies:
    base: ">= 4.11.0.0 && < 5.0"
    Cabal: ">= 2.4.0.1 && < 4.0"
    process: ">= 1.6.3.0"
    PyF:

build-tools:
  alex: ">= 3.2.4"
  happy: ">= 1.19.9"
  BNFC:bnfc: ">= 2.9.4.1"

dependencies:
  array: ">= 0.5.3.0"
  base: ">= 4.7 && < 5"
  text: ">= 1.2.3.1"
  containers:
  bifunctors:
  template-haskell:
  deepseq:
  free-foil: ">= 0.2.0"
  kind-generics-th:

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.STLC.Syntax.Test
        - Language.STLC.Syntax.ErrM
        - Language.STLC.Syntax.Skel

executables:
  STLC:
    main: STLC.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - STLC

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - STLC
      - QuickCheck
      - hspec
      - hspec-discover
      - mtl

  doctests:
    source-dirs:
      - src/
      - test/doctests
    main: Main.hs
    other-modules: []
    dependencies:
      - STLC
      - doctest-parallel
    when:
      - condition: false
        other-modules:
          - Language.STLC.Syntax.Test
          - Language.STLC.Syntax.ErrM
          - Language.STLC.Syntax.Skel
