-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Syntax.

module Language.HMX.Syntax.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

import qualified Data.Data    as C (Data)
import qualified GHC.Generics as C (Generic)

data Program = Program [Command]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Command = CommandCheck Expr | CommandCompute Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Expr
    = EVar VarIdent
    | EConstNat Integer
    | EConstTrue
    | EConstFalse
    | EAdd Expr Expr
    | ESub Expr Expr
    | EIsZero Expr
    | ELam Pattern ScopedExpr
    | EApp Expr Expr
    | EIf Expr Expr Expr
    | ELet Pattern Expr ScopedExpr
    | EFor Pattern Expr Expr ScopedExpr
    | ETyped Expr Type
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Type
    = TForAll TypePattern ScopedType
    | TFunc Type Type
    | TNat
    | TBool
    | TVar VarIdent
    | TUVar UVarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data ScopedExpr = ScopedExpr Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data ScopedType = ScopedType Type
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Pattern = PatternVar VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data TypePattern = PatternType VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

newtype UVarIdent = UVarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

