-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Language.HMX.Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.HMX.Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Language.HMX.Syntax.Abs.VarIdent -> Result
transVarIdent x = case x of
  Language.HMX.Syntax.Abs.VarIdent string -> failure x

transUVarIdent :: Language.HMX.Syntax.Abs.UVarIdent -> Result
transUVarIdent x = case x of
  Language.HMX.Syntax.Abs.UVarIdent string -> failure x

transProgram :: Language.HMX.Syntax.Abs.Program -> Result
transProgram x = case x of
  Language.HMX.Syntax.Abs.Program commands -> failure x

transCommand :: Language.HMX.Syntax.Abs.Command -> Result
transCommand x = case x of
  Language.HMX.Syntax.Abs.CommandCheck expr -> failure x
  Language.HMX.Syntax.Abs.CommandCompute expr -> failure x

transExpr :: Language.HMX.Syntax.Abs.Expr -> Result
transExpr x = case x of
  Language.HMX.Syntax.Abs.EVar varident -> failure x
  Language.HMX.Syntax.Abs.EConstNat integer -> failure x
  Language.HMX.Syntax.Abs.EConstTrue -> failure x
  Language.HMX.Syntax.Abs.EConstFalse -> failure x
  Language.HMX.Syntax.Abs.EAdd expr1 expr2 -> failure x
  Language.HMX.Syntax.Abs.ESub expr1 expr2 -> failure x
  Language.HMX.Syntax.Abs.EIsZero expr -> failure x
  Language.HMX.Syntax.Abs.ELam pattern_ scopedexpr -> failure x
  Language.HMX.Syntax.Abs.EApp expr1 expr2 -> failure x
  Language.HMX.Syntax.Abs.EIf expr1 expr2 expr3 -> failure x
  Language.HMX.Syntax.Abs.ELet pattern_ expr scopedexpr -> failure x
  Language.HMX.Syntax.Abs.EFor pattern_ expr1 expr2 scopedexpr -> failure x
  Language.HMX.Syntax.Abs.ETyped expr type_ -> failure x

transType :: Language.HMX.Syntax.Abs.Type -> Result
transType x = case x of
  Language.HMX.Syntax.Abs.TForAll typepattern scopedtype -> failure x
  Language.HMX.Syntax.Abs.TFunc type_1 type_2 -> failure x
  Language.HMX.Syntax.Abs.TNat -> failure x
  Language.HMX.Syntax.Abs.TBool -> failure x
  Language.HMX.Syntax.Abs.TVar varident -> failure x
  Language.HMX.Syntax.Abs.TUVar uvarident -> failure x

transScopedExpr :: Language.HMX.Syntax.Abs.ScopedExpr -> Result
transScopedExpr x = case x of
  Language.HMX.Syntax.Abs.ScopedExpr expr -> failure x

transScopedType :: Language.HMX.Syntax.Abs.ScopedType -> Result
transScopedType x = case x of
  Language.HMX.Syntax.Abs.ScopedType type_ -> failure x

transPattern :: Language.HMX.Syntax.Abs.Pattern -> Result
transPattern x = case x of
  Language.HMX.Syntax.Abs.PatternVar varident -> failure x

transTypePattern :: Language.HMX.Syntax.Abs.TypePattern -> Result
transTypePattern x = case x of
  Language.HMX.Syntax.Abs.PatternType varident -> failure x
