-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Syntax.

module Language.STLC.Syntax.Abs where

import Prelude (String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

import qualified Data.Data    as C (Data)
import qualified GHC.Generics as C (Generic)

type Program = Program' BNFC'Position
data Program' a = AProgram a [Command' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

type Command = Command' BNFC'Position
data Command' a
    = CommandCheck a (Expr' a) | CommandCompute a (Expr' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

type Expr = Expr' BNFC'Position
data Expr' a
    = EVar a VarIdent
    | EConstNat a NatIdent
    | EConstTrue a TrueIdent
    | EConstFalse a FalseIdent
    | EAdd a (Expr' a) (Expr' a)
    | ESub a (Expr' a) (Expr' a)
    | EIsZero a (Expr' a)
    | ELam a (Pattern' a) (ScopedExpr' a)
    | EApp a (Expr' a) (Expr' a)
    | EIf a (Expr' a) (Expr' a) (Expr' a)
    | ELet a (Pattern' a) (Expr' a) (ScopedExpr' a)
    | ETyped a (Expr' a) (Type' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

type ScopedExpr = ScopedExpr' BNFC'Position
data ScopedExpr' a = AScopedExpr a (Expr' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

type Pattern = Pattern' BNFC'Position
data Pattern' a = PatternVar a VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

type Type = Type' BNFC'Position
data Type' a = TFunc a (Type' a) (Type' a) | TNat a | TBool a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable, C.Data, C.Generic)

newtype NatIdent = NatIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

newtype TrueIdent = TrueIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

newtype FalseIdent = FalseIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    AProgram p _ -> p

instance HasPosition Command where
  hasPosition = \case
    CommandCheck p _ -> p
    CommandCompute p _ -> p

instance HasPosition Expr where
  hasPosition = \case
    EVar p _ -> p
    EConstNat p _ -> p
    EConstTrue p _ -> p
    EConstFalse p _ -> p
    EAdd p _ _ -> p
    ESub p _ _ -> p
    EIsZero p _ -> p
    ELam p _ _ -> p
    EApp p _ _ -> p
    EIf p _ _ _ -> p
    ELet p _ _ _ -> p
    ETyped p _ _ -> p

instance HasPosition ScopedExpr where
  hasPosition = \case
    AScopedExpr p _ -> p

instance HasPosition Pattern where
  hasPosition = \case
    PatternVar p _ -> p

instance HasPosition Type where
  hasPosition = \case
    TFunc p _ _ -> p
    TNat p -> p
    TBool p -> p

