-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for Language.

module Language.STLC.Syntax.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Language.STLC.Syntax.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.STLC.Syntax.Abs.NatIdent where
  prt _ (Language.STLC.Syntax.Abs.NatIdent i) = doc $ showString i
instance Print Language.STLC.Syntax.Abs.TrueIdent where
  prt _ (Language.STLC.Syntax.Abs.TrueIdent i) = doc $ showString i
instance Print Language.STLC.Syntax.Abs.FalseIdent where
  prt _ (Language.STLC.Syntax.Abs.FalseIdent i) = doc $ showString i
instance Print Language.STLC.Syntax.Abs.VarIdent where
  prt _ (Language.STLC.Syntax.Abs.VarIdent i) = doc $ showString i
instance Print (Language.STLC.Syntax.Abs.Program' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.AProgram _ commands -> prPrec i 0 (concatD [prt 0 commands])

instance Print (Language.STLC.Syntax.Abs.Command' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.CommandCheck _ expr -> prPrec i 0 (concatD [doc (showString "check"), prt 0 expr])
    Language.STLC.Syntax.Abs.CommandCompute _ expr -> prPrec i 0 (concatD [doc (showString "compute"), prt 0 expr])

instance Print [Language.STLC.Syntax.Abs.Command' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (Language.STLC.Syntax.Abs.Expr' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.EVar _ varident -> prPrec i 3 (concatD [prt 0 varident])
    Language.STLC.Syntax.Abs.EConstNat _ natident -> prPrec i 3 (concatD [prt 0 natident])
    Language.STLC.Syntax.Abs.EConstTrue _ trueident -> prPrec i 3 (concatD [prt 0 trueident])
    Language.STLC.Syntax.Abs.EConstFalse _ falseident -> prPrec i 3 (concatD [prt 0 falseident])
    Language.STLC.Syntax.Abs.EAdd _ expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "+"), prt 2 expr2])
    Language.STLC.Syntax.Abs.ESub _ expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "-"), prt 2 expr2])
    Language.STLC.Syntax.Abs.EIsZero _ expr -> prPrec i 2 (concatD [doc (showString "iszero"), doc (showString "("), prt 0 expr, doc (showString ")")])
    Language.STLC.Syntax.Abs.ELam _ pattern_ scopedexpr -> prPrec i 1 (concatD [doc (showString "\955"), prt 0 pattern_, doc (showString "."), prt 0 scopedexpr])
    Language.STLC.Syntax.Abs.EApp _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, prt 0 expr2])
    Language.STLC.Syntax.Abs.EIf _ expr1 expr2 expr3 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr1, doc (showString "then"), prt 0 expr2, doc (showString "else"), prt 0 expr3])
    Language.STLC.Syntax.Abs.ELet _ pattern_ expr scopedexpr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 pattern_, doc (showString "="), prt 0 expr, doc (showString "in"), prt 0 scopedexpr])
    Language.STLC.Syntax.Abs.ETyped _ expr type_ -> prPrec i 0 (concatD [prt 0 expr, doc (showString ":"), prt 0 type_])

instance Print (Language.STLC.Syntax.Abs.ScopedExpr' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.AScopedExpr _ expr -> prPrec i 0 (concatD [prt 0 expr])

instance Print (Language.STLC.Syntax.Abs.Pattern' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.PatternVar _ varident -> prPrec i 0 (concatD [prt 0 varident])

instance Print (Language.STLC.Syntax.Abs.Type' a) where
  prt i = \case
    Language.STLC.Syntax.Abs.TFunc _ type_1 type_2 -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "->"), prt 0 type_2])
    Language.STLC.Syntax.Abs.TNat _ -> prPrec i 1 (concatD [doc (showString "Nat")])
    Language.STLC.Syntax.Abs.TBool _ -> prPrec i 1 (concatD [doc (showString "Bool")])
