-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Language.STLC.Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.STLC.Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transNatIdent :: Language.STLC.Syntax.Abs.NatIdent -> Result
transNatIdent x = case x of
  Language.STLC.Syntax.Abs.NatIdent string -> failure x

transTrueIdent :: Language.STLC.Syntax.Abs.TrueIdent -> Result
transTrueIdent x = case x of
  Language.STLC.Syntax.Abs.TrueIdent string -> failure x

transFalseIdent :: Language.STLC.Syntax.Abs.FalseIdent -> Result
transFalseIdent x = case x of
  Language.STLC.Syntax.Abs.FalseIdent string -> failure x

transVarIdent :: Language.STLC.Syntax.Abs.VarIdent -> Result
transVarIdent x = case x of
  Language.STLC.Syntax.Abs.VarIdent string -> failure x

transProgram :: Show a => Language.STLC.Syntax.Abs.Program' a -> Result
transProgram x = case x of
  Language.STLC.Syntax.Abs.AProgram _ commands -> failure x

transCommand :: Show a => Language.STLC.Syntax.Abs.Command' a -> Result
transCommand x = case x of
  Language.STLC.Syntax.Abs.CommandCheck _ expr -> failure x
  Language.STLC.Syntax.Abs.CommandCompute _ expr -> failure x

transExpr :: Show a => Language.STLC.Syntax.Abs.Expr' a -> Result
transExpr x = case x of
  Language.STLC.Syntax.Abs.EVar _ varident -> failure x
  Language.STLC.Syntax.Abs.EConstNat _ natident -> failure x
  Language.STLC.Syntax.Abs.EConstTrue _ trueident -> failure x
  Language.STLC.Syntax.Abs.EConstFalse _ falseident -> failure x
  Language.STLC.Syntax.Abs.EAdd _ expr1 expr2 -> failure x
  Language.STLC.Syntax.Abs.ESub _ expr1 expr2 -> failure x
  Language.STLC.Syntax.Abs.EIsZero _ expr -> failure x
  Language.STLC.Syntax.Abs.ELam _ pattern_ scopedexpr -> failure x
  Language.STLC.Syntax.Abs.EApp _ expr1 expr2 -> failure x
  Language.STLC.Syntax.Abs.EIf _ expr1 expr2 expr3 -> failure x
  Language.STLC.Syntax.Abs.ELet _ pattern_ expr scopedexpr -> failure x
  Language.STLC.Syntax.Abs.ETyped _ expr type_ -> failure x

transScopedExpr :: Show a => Language.STLC.Syntax.Abs.ScopedExpr' a -> Result
transScopedExpr x = case x of
  Language.STLC.Syntax.Abs.AScopedExpr _ expr -> failure x

transPattern :: Show a => Language.STLC.Syntax.Abs.Pattern' a -> Result
transPattern x = case x of
  Language.STLC.Syntax.Abs.PatternVar _ varident -> failure x

transType :: Show a => Language.STLC.Syntax.Abs.Type' a -> Result
transType x = case x of
  Language.STLC.Syntax.Abs.TFunc _ type_1 type_2 -> failure x
  Language.STLC.Syntax.Abs.TNat _ -> failure x
  Language.STLC.Syntax.Abs.TBool _ -> failure x
